import "@/public/css/globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Navbar/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
