import "@/public/css/globals.css";
import Navbar from "@/Components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Navbar />
      <div className="">{children}</div>
    </div>
  );
}
